[Metadata]
 Name                                     = Elemetry
 Version                                  = 1.0.0a
 Author                                   = deflore08 (deflore08@daid-art.online) | https://www.deviantart.com/deflore08
 License                                  = Creative Commons Attribution-Non-Commercial-Share Alike 4.0
 Information                              = Suite for PC monitoring

[Variables]

 DEFAULT_Phi                              = 1.618

 DEFAULT_MainColor                        = 93, 255, 190, 255
 DEFAULT_SecondaryColor                   = 200,150,255,255
 DEFAULT_MainArcRadius                    = 230

 DEFAULT_X_Axis                           = (#MainArcRadius# * 0.01 + 1)
 DEFAULT_Y_Axis                           = (#MainArcRadius# * 0.01 + 1)

; --- FONTS

 DEFAULT_MainFont                         = BUNGEE HAIRLINE
