[Metadata]
 Name                             = Elemetry
 Version                          = 1.0.0a
 Author                           = deflore08 (deflore08@daid-art.online) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 4.0
 Information                      = Suite for PC monitoring

[Variables]

; --- CONSTANTS

 Phi                              = 1.618

; --- COLORS

 MainColor                        = 255,255,255,255
 SecondaryColor                   = 255,255,255,255

; --- FONTS

 MainFont                         = BUNGEE HAIRLINE

; --- DIMENSIONS

 MainArcRadius                    = 230

 X_Axis                           =10
 Y_Axis                           =10