[Metadata]
 Name                             = Elemetry
 Version                          = 1.0.0a
 Author                           = deflore08 (deflore08@daid-art.online) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 4.0
 Information                      = Suite for PC monitoring

[Variables]

 sensors                          = sensors
 calculations                     = calculations
 meters                           = meters
 texts                            = texts
 texts_static                     = texts_static
 texts_dynamic                    = texts_dynamic
 texts_calculations               = texts_calculations
 updater                          = updater
 debug                            = debug
 substrate                        = substrate

; --- CPU

 cpu                              = cpu
 cpu_sensors                      = cpu_sensors
 cpu_meters                       = cpu_meters
 cpu_calculations                 = cpu_calculations

; --- GPU

 gpu                              = gpu
 gpu_sensors                      = gpu_sensors
 gpu_meters                       = gpu_meters
 cpu_calculations                 = cpu_calculations

; --- RAM

 ram                              = ram
 ram_sensors                      = ram_sensors
 ram_meters                       = ram_meters
 ram_calculations                 = ram_calculations

; --- VRAM

 vram                             = vram
 vram_sensors                     = vram_sensors
 vram_meters                      = vram_meters
 vram_calculations                = vram_calculations

; --- NET

 net                              = net
 net_sensors                      = net_sensors
 net_meters                       = net_meters
 net_calculations                 = net_calculations

; --- DRIVES

 drives                           = drives
 drives_sensors                   = drives_sensors
 drives_meters                    = drives_meters
 drives_calculations              = drives_calculations

; --- FRAMES

 frame_one                        = frame_one
 frame_two                        = frame_two
 frame_three                      = frame_three
 frame_four                       = frame_four
 frame_five                       = frame_five
 frame_six                        = frame_six
 frame_seven                      = frame_seven
 frame_eight                      = frame_eight
 frame_nine                       = frame_nine
 frame_ten                        = frame_ten