[Metadata]
 Name                             = Elemetry
 Version                          = 1.0.0a
 Author                           = deflore08 (deflore08@daid-art.online) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 4.0
 Information                      = Suite for PC monitoring

[Variables]

 sensors                          = sensors
 updater                          = updater
 debug                            = debug
 substrate                        = substrate

; --- FRAMES

 frame_one                        = frame_one
 frame_two                        = frame_two
 frame_three                      = frame_three
 frame_four                       = frame_four
 frame_five                       = frame_five
 frame_six                        = frame_six
 frame_seven                      = frame_seven
 frame_eight                      = frame_eight
 frame_nine                       = frame_nine
 frame_ten                        = frame_ten