[Metadata]
 Name                             = Elemetry
 Version                          = 1.0.0a
 Author                           = deflore08 (deflore08@daid-art.online) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 4.0
 Information                      = Suite for PC monitoring

[style.text.1x]
 FontColor                        = #MainColor#
 FontSize                         = [formula.1xFontSize]
 FontFace                         = #MainFont#
 StringAlign                      = CenterCenter
 StringStyle                      = Bold
 NumOfDecimals                    = 0
 AntiAlias                        = 1

[style.text.2x]
 FontColor                        = #MainColor#
 FontSize                         = [formula.2xFontSize]
 FontFace                         = #MainFont#
 StringAlign                      = CenterCenter
 StringStyle                      = Bold
 NumOfDecimals                    = 0
 AntiAlias                        = 1

[style.text.3x]
 FontColor                        = #MainColor#
 FontSize                         = [formula.3xFontSize]
 FontFace                         = #MainFont#
 StringAlign                      = CenterCenter
 StringStyle                      = Bold
 NumOfDecimals                    = 0
 AntiAlias                        = 1

[style.text.4x]
 FontColor                        = #MainColor#
 FontSize                         = [formula.4xFontSize]
 FontFace                         = #MainFont#
 StringAlign                      = CenterCenter
 StringStyle                      = Bold
 NumOfDecimals                    = 0
 AntiAlias                        = 1


